# Generated by Django 5.2.16 on 2026-08-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0006_add_audit_read_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshtoken',
            name='device_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='issued_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
