# Generated by Django 5.2.16 on 2026-08-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(max_length=64)),
                ('actor_id', models.BigIntegerField(blank=True, null=True)),
                ('actor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('target_type', models.CharField(blank=True, max_length=64, null=True)),
                ('target_id', models.CharField(blank=True, max_length=255, null=True)),
                ('outcome', models.CharField(default='success', max_length=16)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['actor_id', 'created_at'], name='audit_actor_created_idx'), models.Index(fields=['action', 'created_at'], name='audit_action_created_idx')],
            },
        ),
    ]
